name: Deploy To Ali Cloud

on:
  push:
    branches: ['main']

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build project
        run: pnpm vite build --base=http://cdn.liangjiayu.top/react-admin-vite/prod/
      - name: Upload files to OSS
        uses: JohnGuan/oss-upload-action@main
        with:
          key-id: ${{ secrets.ALICLOUD_ACCESS_KEY }}
          key-secret: ${{ secrets.ALICLOUD_SECRET_KEY }}
          region: oss-cn-guangzhou
          bucket: fast-fe-static
          assets: |
            dist/**:/react-admin-vite/prod/