name: Deploy To GitHub Pages

on:
  # 仅在推送到默认分支时运行
  push:
    branches: ['main']

  # 这个选项可以使你手动在 Action tab 页面触发工作流
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限，以允许部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build project
        run: pnpm vite build --base=http://cdn.liangjiayu.top/react-admin-vite/prod/
      - name: upload files to OSS
        uses: JohnGuan/oss-upload-action@main
        with:
          key-id: ${{ secrets.ALICLOUD_ACCESS_KEY }}
          key-secret: ${{ secrets.ALICLOUD_SECRET_KEY }}
          endpoint: oss-cn-guangzhou.aliyuncs.com
          bucket: fast-fe-static
          assets: |
            dist/**:/react-admin-vite/prod/