name: Deploy To Ali Cloud

on:
  push:
    branches: ['main']

  workflow_dispatch:
    inputs:
      deploy_env:
        description: '部署环境'  
        required: true
        default: 'prod'
        type: choice
        options:
          - daily
          - prod

env:
  DEPLOY_ENV: ${{ inputs.deploy_env || 'prod' }}
  CDN_URL: //cdn.liangjiayu.top
  APP_NAME: react-admin-vite

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build project
        run: pnpm vite build --base="${{ env.CDN_URL }}/${{ env.APP_NAME }}/${{ env.DEPLOY_ENV }}/"
      - name: Upload files to OSS
        uses: JohnGuan/oss-upload-action@main
        with:
          key-id: ${{ secrets.ACCESS_KEY_ID }}
          key-secret: ${{ secrets.ACCESS_KEY_SECRET }}
          region: oss-cn-guangzhou
          bucket: fast-fe-static
          assets: |
            dist/**:/${{ env.APP_NAME }}/${{ env.DEPLOY_ENV }}/

      - name: Deploy Success
        run: |
          echo "✅ 已部署到 ${{ env.DEPLOY_ENV  }} 环境"
          echo "访问地址: ${{ env.CDN_URL }}/${{ env.APP_NAME }}/${{ env.DEPLOY_ENV }}/"