name: Deploy To Ali Cloud

on:
  push:
    branches: ['main']

  workflow_dispatch:
    inputs:
      deploy_env:
        description: '部署环境'  
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - prod

env:
  CDN_URL: //cdn.liangjiayu.top
  OSS_TARGET_PATH: /react-admin-vite/${{ inputs.deploy_env }}/

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build project
        run: pnpm vite build --base="${{ env.CDN_URL }}${{ env.OSS_TARGET_PATH }}"
      - name: Upload files to OSS
        uses: JohnGuan/oss-upload-action@main
        with:
          key-id: ${{ secrets.ALICLOUD_ACCESS_KEY }}
          key-secret: ${{ secrets.ALICLOUD_SECRET_KEY }}
          region: oss-cn-guangzhou
          bucket: fast-fe-static
          assets: |
            dist/**:${{ env.OSS_TARGET_PATH }}

      - name: Deploy Success
        run: |
          echo "✅ 已部署到 ${{ inputs.deploy_env  }} 环境"
          echo "访问地址: ${{ env.CDN_URL }}${{ env.OSS_TARGET_PATH }}"